name: run pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
    - name: Install pytest
      run: pip install pytest
    - name: Install pandas
      run: pip install pandas
    - name: Test with pytest
      run: pytest
